[package]
name = "acheron"
version = "0.1.0"
authors = ["Robbie McKinstry <robbie@hashicorp.com>"]
edition = "2018"
license = "MIT"
description = "A simple SAT solver"

[badges]
maintenance = { status = "experimental" }

[dependencies]
clap = "2.32.0"
im = "12.3.3"
